import './globals.css';
import { Inter } from 'next/font/google';
import { Header } from '@/src/components/Layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={(inter.className, 'bg-[#FCF7F4]')}>
        <Header />
        <div className='w-full h-full pt-20'>{children}</div>
      </body>
    </html>
  );
}
