name: SCANNER-Build-Test-on-PR CI/CD

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 20.3
        uses: actions/setup-node@v2
        with:
          node-version: 20.3

      - name: Install Dependencies
        run: npm install

      - name: env
        run: echo "NEXT_PUBLIC_SERVER_URL=${{ vars.NEXT_PUBLIC_SERVER_URL }}" >> $GITHUB_ENV

      - name: Build Project
        run: npm run build